name: app
description: "A budget-tracking application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_localization: ^0.3.2
  go_router: ^16.1.0
  intl: any
  flutter_colorpicker: ^1.1.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  google_sign_in: ^7.1.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.4.2
  flutter_dotenv: ^6.0.0
  file_picker: ^10.3.2
  image_cropper: ^9.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/saira/
    - assets/.env

  fonts:
    - family: Saira
      fonts:
        - asset: assets/fonts/saira/Saira-VariableFont_wdth-wght.ttf
        - asset: assets/fonts/saira/Saira-Italic-VariableFont_wdth-wght.ttf
          style: italic

flutter_intl:
  enabled: true
